import { ClientAuthContext } from "~/context/ClientAuthContext";
import { ThemeProvider } from "~/context/ThemeContext";
import "~/styles/globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background-light-gray dark:bg-primary-dark-gray transition-colors">
        <ClientAuthContext>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </ClientAuthContext>
      </body>
    </html>
  );
}
